# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmilPoc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmilPoc
  pod 'RNMobileCenter', '~> 0.2.0'
  pod 'MobileCenter', '~> 0.4.0'

  

  target 'SmilPocTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SmilPoc-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SmilPoc-tvOS

  target 'SmilPoc-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
